
#ifndef HABleServiceDefs_h_
#define HABleServiceDefs_h_

// service UUID defs
#define BUTTON1_SERVICE_UUID	0xA000
#define BUTTON2_SERVICE_UUID    0xA001
#define LIGHT_SERVICE_UUID		0xA002
#define LED_SERVICE_UUID			0xA003
#define RGBLED_SERVICE_UUID		0xA004
#define PLUG_SERVICE_UUID			0xA005
#define DIMMER_SERVICE_UUID		0xA006

// charateristic UUID defs
#define BUTTON_STATE_CHARACTERISTIC_UUID	0xA100
#define BUTTON1_STATE_CHARACTERISTIC_UUID	0xA101
#define BUTTON2_STATE_CHARACTERISTIC_UUID	0xA102
#define LED_STATE_CHARACTERISTIC_UUID	0xA103
#define DIMMER_STATE_CHARACTERISTIC_UUID	0xA104
#define DIMMER_ENERGY_CHARACTERISTIC_UUID	0xA105
#define LIGHT_STATE_CHARACTERISTIC_UUID 	0xA106


// common characteristics
#define BATTERY_STATE_CHARACTERISTIC_UUID	0xA200


// MAC address indeces
#define HOME_ID_IDX	0
#define DEV_ID_IDX	5


#endif

